New Chinese translation
jurialmunkey/skin.arctic.fuse pull request #281
Opened 2023-12-11 08:33 UTC by kalifun

New Chinese translation documents

2023-12-11 09:40 UTC, jurialmunkey requested changes
Thanks for submitting this. There are few issues where `$INFO[]` tags that shouldn't be translated have been translated. These will break in the skin if you change them.

Anything inside square brackets `[ ]` should not be translated.

2023-12-11 09:40 UTC, jurialmunkey commented on language/resource.language.zh_cn/strings.po
> +msgstr "您已经观看了$INFO[Window(Home)。$INFO[Window(Home)的财产(TVShows.Watched),[COLOR=main_fg_90][B],[/B][/COLOR]]。财产（TVShows.Count），[COLOR=main_fg_90][B]，[/B][/COLOR]]您图书馆中的电视节目。[CR]剧集$INFO[窗口（主页）。属性（最新剧集.
Don't translate the `$INFO[]` tags as these are skin values.

2023-12-11 09:40 UTC, jurialmunkey commented on language/resource.language.zh_cn/strings.po
> +msgstr "您已经观看了$INFO[Window(Home)。$INFO[Window(Home)的财产(Movies.Watched),[COLOR=main_fg_90][B],[/B][/COLOR]]。库中的属性（Movies.Count），[COLOR=main_fg_90][B]，[/B][/COLOR]]电影。[CR]电影$INFO[窗口（主页）。属性（最新电影.1。标题），[
Same here.

2023-12-11 09:40 UTC, jurialmunkey commented on language/resource.language.zh_cn/strings.po
> +msgstr "您有$INFO[窗口（主页）。Property(Movies.Count),[COLOR=main_fg_90][B],[/B][/COLOR]] movies$COMMA $INFO[Window(Home).Property(TVShows.Count),[COLOR=main_fg_90][B],[/B][/COLOR]]电视节目$COMMA $INFO[Window(Ho
Add here.

2023-12-11 09:40 UTC, jurialmunkey commented on language/resource.language.zh_cn/strings.po
> +msgstr "您总共观看了$INFO[Window(Home)。Property(TMDbHelper.TraktStats.Total.Minutes_d),[COLOR=main_fg_90][B],[/B][/COLOR]] days$COMMA $INFO[Window(Home).Property(TMDbHelper.TraktStats.Total.Minutes_h),[COL
Add here.

2023-12-11 09:40 UTC, jurialmunkey commented on language/resource.language.zh_cn/strings.po
> +msgstr "您已经观看了$INFO[Window(Home)。Property(TMDbHelper.TraktStats.Movies.Watched),[COLOR=main_fg_90][B],[/B][/COLOR]]电影和$INFO[Window(Home).Property(TMDbHelper.TraktStats.Shows.Watched),[COLOR=main_fg_9
Add here.

2023-12-11 09:40 UTC, jurialmunkey commented on language/resource.language.zh_cn/strings.po
> +msgstr "$INFO[Container(22001)的小部件。主页屏幕上的ListItem.Label，[LOWERCASE]，[/LOWERCASE]]图标"
Add here.

2023-12-11 09:40 UTC, jurialmunkey commented on language/resource.language.zh_cn/strings.po
> +msgstr "$INFO[Container(22001)的小部件。ListItem.Label，[LOWERCASE]，[/LOWERCASE]]类别"
Add Here.

2023-12-11 09:40 UTC, jurialmunkey commented on language/resource.language.zh_cn/strings.po
> +msgstr "编辑 $INFO[Container(22001)。ListItem.Label，[LOWERCASE]，[/LOWERCASE]]聚光灯"
Add Here

2023-12-11 09:40 UTC, jurialmunkey commented on language/resource.language.zh_cn/strings.po
> +msgstr "编辑 $INFO[Container(22001)。ListItem.Label，[LOWERCASE]，[/LOWERCASE]]子菜单"
Add Here.

2023-12-11 09:40 UTC, jurialmunkey commented on language/resource.language.zh_cn/strings.po
> +msgstr "编辑 $INFO[Container(22001)。ListItem.Label，[LOWERCASE]，[/LOWERCASE]]小部件"
Add Here.

2023-12-11 09:40 UTC, jurialmunkey commented on language/resource.language.zh_cn/strings.po
> +msgstr "$INFO[Container(22001)内的聚光灯。ListItem.Label，[LOWERCASE]，[/LOWERCASE]] hub"
Here

2023-12-11 09:40 UTC, jurialmunkey commented on language/resource.language.zh_cn/strings.po
> +msgstr "$INFO[Container(22001)内的类别。ListItem.Label，[LOWERCASE]，[/LOWERCASE]] hub"
Here.

2023-12-11 09:40 UTC, jurialmunkey commented on language/resource.language.zh_cn/strings.po
> +msgstr "$INFO[Container(22001)中的小部件。ListItem.Label，[LOWERCASE]，[/LOWERCASE]] hub"
Here.

2023-12-11 13:27 UTC, kalifun commented
> Thanks for submitting this. There are few issues where `$INFO[]` tags that shouldn't be translated have been translated. These will break in the skin if you change them.
> 
> Anything inside square brackets `[ ]` should not be translated.

I'm very sorry, I didn't notice. I will revise it before submitting it.

2023-12-11 14:30 UTC, kalifun commented
I have tried to modify it. Please help me see if there is any problem. @jurialmunkey

2023-12-13 19:29 UTC, icarok99 approved these changes

2023-12-14 01:05 UTC, merged