Update strings.po Spanish Language
jurialmunkey/skin.arctic.fuse pull request #538
Opened 2024-03-04 18:59 UTC by gtkingbuild

2024-03-04 19:26 UTC, icarok99 commented
Strings.po It is out of date and is missing some texts 

https://github.com/icarok99/skin.arctic.fuse/blob/omega/language/resource.language.es_es/strings.po

2024-03-04 19:29 UTC, icarok99 commented
> Strings.po It is out of date and is missing some texts
> 
> https://github.com/icarok99/skin.arctic.fuse/blob/omega/language/resource.language.es_es/strings.po

Create a 2 branch with your translation and then replace with that translation and you will check which texts are missing

2024-03-08 08:53 UTC, jurialmunkey requested changes
Hi thanks for submitting this translation. There's quite a lot of diff type conflicts in the file that need to be resolves (all the "stash changes" lines etc.). IF those can be fixed up then I can merge.

2024-03-08 08:53 UTC, jurialmunkey commented on language/resource.language.es_es/strings.po
> +>>>>>>> Stashed changes
These need to be fixed

2024-03-08 09:01 UTC, icarok99 commented
> Hi thanks for submitting this translation. There's quite a lot of diff type conflicts in the file that need to be resolves (all the "stash changes" lines etc.). IF those can be fixed up then I can merge.

Open another pull request with the changes.

2024-03-10 07:35 UTC, jurialmunkey commented
Add in #551

2024-03-10 07:35 UTC, closed without merging